AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters: 
  # StringParamWithNoProps:
  #   Type: String
  # StringParamWithFullProps:
  #   Description: this is a string param with full properties
  #   Type: String
  #   Default: defaultVal1
  #   AllowedPattern: defaultVal[1-3]
  #   AllowedValues:
  #     - defaultVal1
  #     - defaultVal2
  #     - defaultVal3
  #   ConstraintDescription: this is constraint description message
  #   MaxLength: 11
  #   MinLength: 11
  #   NoEcho: true
  # SecretStringParam:
  #   Description: this is a secret string param with full properties
  #   Type: String
  #   NoEcho: true

  # CdlParamWithNoProps:
  #   Type: CommaDelimitedList
  # CdlParamWithFullProps:
  #   Description: this is a comma delimited list param with full properties
  #   Type: CommaDelimitedList
  #   Default: defaultVal1,defaultVal2


  # NumberParamWithNoProps:
  #   Type: Number
  # NumberParamWithFullProps:
  #   Description: this is a number param with full propertirs
  #   Type: Number
  #   Default: 10
  #   AllowedValues:
  #     - 10
  #     - 100
  #     - 1000
  #   MaxValue: 1000
  #   MinValue: 10

  # ListNumberParamWithNoProps:
  #   Type: List<Number>
  # ListNumberWithFullProps:
  #   Description: this is a list number param with full properties
  #   Type: List<Number>
  #   Default: 10,100

  # AzParam:
  #   Type: AWS::EC2::AvailabilityZone::Name
  #   Description: this is a az param
  # AzListParam:
  #   Type: List<AWS::EC2::AvailabilityZone::Name>
  #   Description: this is a az list param


  # SsmNameParam:
  #   Type: AWS::SSM::Parameter::Name
  #   Description: this is a ssm name param 

  # SsmValueParam:
  #   Type: AWS::SSM::Parameter::Value<String>
  #   Description: this is a ssm value param 
  
  # SsmValueListParam:
  #   Type: AWS::SSM::Parameter::Value<List<String>>
  #   Description: this is a ssm value list param 

  # SsmValueCdlParam:
  #   Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
  #   Description: this is a ssm value cdl param 



  # AmiParam:
  #   Type: AWS::EC2::Image::Id
  #   Description: this is a ami param

  # InstanceIdParam:
  #   Description: this is a instance id param
  #   Type: AWS::EC2::Instance::Id

  # KeyNameParam:
  #   Description: this is a key name param 
  #   Type: AWS::EC2::KeyPair::KeyName

  # SgNameParam:
  #   Description: this is a sg name param 
  #   Type: AWS::EC2::SecurityGroup::GroupName

  # SgIdParam:
  #   Description: this is a sg id param
  #   Type: AWS::EC2::SecurityGroup::Id

  # SubnetIdParam:
  #   Description: this is as subnet id param
  #   Type: AWS::EC2::Subnet::Id
  # VpcIdParam:
  #   Description: this is a vpc id param
  #   Type: AWS::EC2::VPC::Id
  
  # HostedZoneIdParam:
  #   Description: this is a hosted zone id param
  #   Type: AWS::Route53::HostedZone::Id

  # AzNameListParam:
  #   Description: this is az name list param 
  #   Type: List<AWS::EC2::AvailabilityZone::Name>

  # AmiIdListParam:
  #   Description: this is ami id list param 
  #   Type: List<AWS::EC2::Image::Id>

  # InstanceIdListParam:
  #   Description: this is instance is list param
  #   Type: List<AWS::EC2::Instance::Id>
  # SgNameListParam:
  #   Description: this is sg name list param
  #   Type: List<AWS::EC2::SecurityGroup::GroupName>
  # SgIdListParam:
  #   Description: this is sg id list param
  #   Type: List<AWS::EC2::SecurityGroup::Id>
  # SubnetIdListParam:
  #   Description: this is subnet id list param
  #   Type: List<AWS::EC2::Subnet::Id>
  # VolumeIdParam:
  #   Description: this is a volume id param 
  #   Type: AWS::EC2::Volume::Id
  # VolumeIdListParam:
  #   Description: this is volume id list param
  #   Type: List<AWS::EC2::Volume::Id>
  # VpcIdListParam:
  #   Description: this is vpc id list param 
  #   Type: List<AWS::EC2::VPC::Id>
  # HostedZoneIdListParam:
  #   Description: this is hosted zone id list param
  #   Type: List<AWS::Route53::HostedZone::Id>

  SsmAzNameParam:
    Description: this is ssm az name param
    Type: AWS::SSM::Parameter::Value<AWS::EC2::AvailabilityZone::Name>
  SsmAzListParam:
    Description: 
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::AvailabilityZone::Name>>


Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub test-bucket-2022-02-12-${StringParamWithFullProps}

Outputs:
  output:
    Description: this is a output
    Value: !Ref StringParamWithNoProps